### ISSUE TITLE
Meson build cannot find "python" module

### ISSUE THREAD

**Issue by mcclauba** [AravisProject/aravis#322]
**Describe the bug**
Running command, _sudo meson build_ returns error: 
    tests/meson.build:29:2: ERROR: Module "python" does not exist

**To Reproduce**
git cloned aravis into /usr/3rdparty directory
Run build command

**Expected behavior**
A successful build

**Platform description:**
 - Aravis version 0.8
 - OS: Ubuntu 18.04
 - Hardware: Nvidia Xavier 16GB on Connect Tech Rogue Carrier board

**Additional context**
I have both python 2.7 and python 3.6.9 installed.  Have set _sudo update-alternatives --config python_ to point to python 3.6.9 in auto-mode, however this issue persisted when python 2.7 was in auto-mode also.

**Comment by mcclauba** [comment]
Building with tests disabled was not the simple fix that I had hoped.  Editing meson_options.txt so that:
_option('tests', type: 'boolean', value: false,
  description: 'Build tests')_

received the following error upon _sudo ninja install_:

Building documentation for aravis
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/gtkdochelper.py", line 231, in run
    options.mode)
  File "/usr/share/meson/mesonbuild/scripts/gtkdochelper.py", line 96, in build_gtkdoc
    abs_out, os.path.basename(f_abs)))
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/3rdparty/aravis/docs/reference/aravis/../tests/arvexample.c'
Failed to run install script '/usr/bin/python3 /usr/bin/meson --internal gtkdoc --sourcedir=/usr/3rdparty/aravis --builddir=/usr/3rdparty/aravis/build --subdir=docs/reference/aravis --headerdirs=/usr/3rdparty/aravis/src@@/usr/3rdparty/aravis/build/src --mainfile=aravis-docs.xml --modulename=aravis --mode=auto --scanargs=--ignore-headers=arvbufferprivate.h arvchunkparserprivate.h arvdeviceprivate.h arvfakedeviceprivate.h arvfakeinterfaceprivate.h arvfakestreamprivate.h arvgcconverterprivate.h arvgcfeaturenodeprivate.h arvgcregisternodeprivate.h arvgcswissknifeprivate.h arvgvcpprivate.h arvgvdeviceprivate.h arvgvinterfaceprivate.h arvgvspprivate.h arvgvstreamprivate.h arvinterfaceprivate.h arvmiscprivate.h arvrealtimeprivate.h arvstreamprivate.h arvwakeupprivate.h arvuvcpprivate.h arvuvdeviceprivate.h arvuvinterfaceprivate.h arvuvstreamprivate.h arvuvspprivate.h arv.h arvconfig.h arvenumtypes.h arvenumtypesprivate.h@@--rebuild-types --gobjects-types-file=aravis.types --content-files=/usr/3rdparty/aravis/docs/reference/aravis/aravis-overview.xml@@/usr/3rdparty/aravis/docs/reference/aravis/aravis-gv.xml@@../tests/arvexample.c@@../tests/arvchunkparsertest.c --installdir=aravis-0.8 --cflags=-I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -pthread -I/usr/include/libxml2 -I/usr/include/libusb-1.0 --ldflags=-L/usr/3rdparty/aravis/build/src -Wl,-rpath,/usr/3rdparty/aravis/build/src -laravis-0.8 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lxml2 -lz -lm -lusb-1.0 --cc=cc --ld=cc'
FAILED: meson-install
/usr/bin/python3 /usr/bin/meson --internal install /usr/3rdparty/aravis/build/meson-private/install.dat
ninja: build stopped: subcommand failed.

**Comment by mcclauba** [comment]
Without doing any further configuration of my system's python package (as both 'python' and 'python3' commands work), I have been able to successfully build Aravis with introspection and documentation options set to 'false.'

However, after a successful install, GStreamer is unable to load aravissrc.  The plug-in is blacklisted and returns the following:  

~$ gst-inspect-1.0 -b

(gst-plugin-scanner:6590): GStreamer-WARNING **: 11:43:07.022: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstaravis.0.8.so': libaravis-0.8.so.0: cannot open shared object file: No such file or directory
Blacklisted files:
  libgstaravis.0.8.so


...By the way, with my implementation I need to create a symbolic link of the libgstaravis.0.8.so that was created through ninja installation in /usr/local/lib/aarch64-linux-gnu/gstreamer-1.0 to where my GStreamer seaches for plugins in /usr/lib/aarch64-linux-gnu/gstreamer-1.0...

**Comment by mcclauba** [comment]
Ignore this.  I build aravis with meson version 0.45 because that is all the _apt install meson_ could provide.  After rebuilding with the most recent version of meson, everything worked.  SOrry if I wasted somebody's time.
