### ISSUE TITLE
CI failing due to py3.5 and pip incompatibility

### ISSUE THREAD

**Issue by spatel-cog** [AravisProject/aravis#473]
**Describe the bug**
CI breaking due to deprecation of python 3.5

**To Reproduce**
 Installing the latest pip-21.0.1  results in the following error when installing meson
```
root@02190cab86bc:/# pip3 install 'meson==0.47'
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 16, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/entrypoints.py", line 3, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
```
**Expected behavior**
Successful installation of meson

**Camera description:**
NA

**Platform description:**
 - Aravis version: 0.8.6
 - OS: Ubuntu 16.04 LTS
 - Hardware: Docker container 

**Additional context**
The fix is:
```sudo pip3 install --upgrade setuptools pip==20.3.4```
See my patch in 
https://github.com/AravisProject/aravis/pull/472/commits/129d0ff7e937775af8c820a2bc9e264c0c8ef9cd

**Comment by spatel-cog** [comment]
Fixed by commit https://github.com/AravisProject/aravis/commit/38197f5a79d6e871d1ad26a7f5eb9e33c18ddf23
