### ISSUE TITLE
gi-docgen documenation build error on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by nulijiabei** [AravisProject/aravis#645]
Found ninja-1.10.2.git.kitware.jobserver-1 at /usr/local/bin/ninja
root@lh-QM9000H-2C:~/aravis-main# cd build/
root@lh-QM9000H-2C:~/aravis-main/build# ninja 
[145/184] Generating src/Aravis-0.8.gir with a custom command
g-ir-scanner: link: x86_64-linux-gnu-gcc -pthread -o /root/aravis-main/build/tmp-introspect90rm7hdr/Aravis-0.8 /root/aravis-main/build/tmp-introspect90rm7hdr/Aravis-0.8.o -L. -Wl,-rpath,. -Wl,--no-as-needed -L/root/aravis-main/build/src -Wl,-rpath,/root/aravis-main/build/src -laravis-0.8 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lxml2 -lz -lm -lusb-1.0 -lgirepository-1.0 -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
[184/184] Generating docs/reference/aravis/aravis-doc with a custom command
FAILED: docs/reference/aravis/aravis-0.8 
/root/aravis-main/subprojects/gi-docgen/gi-docgen.py generate --quiet --no-namespace-dir --add-include-path=/root/aravis-main/build/docs/reference/aravis/../../../src --config=docs/reference/aravis/aravis.toml --output-dir=docs/reference/aravis/aravis-0.8 --content-dir=/root/aravis-main/docs/reference/aravis src/Aravis-0.8.gir
Traceback (most recent call last):
  File "/root/aravis-main/subprojects/gi-docgen/gidocgen/gidocmain.py", line 74, in run
    res = options.run_func(options)
  File "/root/aravis-main/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 3115, in run
    gen_reference(conf, options, parser.get_repository(), templates_dir, theme_conf, content_dirs, output_dir)
  File "/root/aravis-main/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2958, in gen_reference
    content_files = gen_content_files(config, theme_config, content_dirs, ns_dir, jinja_env, namespace)
  File "/root/aravis-main/subprojects/gi-docgen/gidocgen/gdgenerate.py", line 2594, in gen_content_files
    md = markdown.Markdown(extensions=utils.MD_EXTENSIONS, extension_configs=utils.MD_EXTENSIONS_CONF)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 99, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 160, in build_extension
    return ext(**configs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/toc.py", line 311, in __init__
    super(TocExtension, self).__init__(**kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 42, in __init__
    self.setConfigs(kwargs)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 73, in setConfigs
    self.setConfig(key, value)
  File "/usr/lib/python3/dist-packages/markdown/extensions/__init__.py", line 61, in setConfig
    if isinstance(self.config[key][0], bool):
KeyError: 'permalink_class'
ninja: build stopped: subcommand failed.

**Comment by EmmanuelP** [comment]
It looks like gi-docgen is not working reliably on every platform.

I have pushed a path that disables the documentation build by default.

Meanwhile, you can disable it using:

```
meson configure -Ddocumentation=disabled
```

**Comment by nulijiabei** [comment]
thank you
